version: '3'

services:
  backend:
    build: .
    image: dias1618/negai-backend
    container_name: negai-backend
    ports:
        - 3000:3000
    restart: on-failure
    networks:
      - postgres-network
      
networks:
  postgres-network:
    driver: bridge